sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'travis-ci@design4.pro'
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
