sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
before_install:
  - git remote set-branches origin master && git fetch
  - git checkout master
  - git branch
  - git log
script:
  - npm run test:debug
  - npm run test:check-coverage
after_success:
  - npm run report-coverage
